version: 2.1

orbs:
  slack:circleci/slack@4.10.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - slack/notify:
          channel: 'C04B28F4YHF, C04ALLNRGBF'
          branch_pattern: main
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "Friday Stage DB refrersh has been complete",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
          
workflows:
  my-workflow:
    jobs:
      - hello-job:
          context: slack-secrets
     
